// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CardsColumns holds the columns for the "cards" table.
	CardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "energy", Type: field.TypeInt},
		{Name: "target", Type: field.TypeString},
		{Name: "block", Type: field.TypeInt},
		{Name: "damage", Type: field.TypeInt},
		{Name: "power", Type: field.TypeJSON},
		{Name: "action", Type: field.TypeJSON},
		{Name: "description", Type: field.TypeString},
		{Name: "image", Type: field.TypeString},
		{Name: "upgrade", Type: field.TypeInt},
	}
	// CardsTable holds the schema information for the "cards" table.
	CardsTable = &schema.Table{
		Name:       "cards",
		Columns:    CardsColumns,
		PrimaryKey: []*schema.Column{CardsColumns[0]},
	}
	// LeaderboardsColumns holds the columns for the "leaderboards" table.
	LeaderboardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "playerID", Type: field.TypeString, Unique: true},
		{Name: "counts", Type: field.TypeInt},
	}
	// LeaderboardsTable holds the schema information for the "leaderboards" table.
	LeaderboardsTable = &schema.Table{
		Name:       "leaderboards",
		Columns:    LeaderboardsColumns,
		PrimaryKey: []*schema.Column{LeaderboardsColumns[0]},
	}
	// MonstersColumns holds the columns for the "monsters" table.
	MonstersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "Type", Type: field.TypeString},
		{Name: "HP", Type: field.TypeInt},
		{Name: "block", Type: field.TypeInt},
		{Name: "power", Type: field.TypeJSON},
		{Name: "actionName", Type: field.TypeJSON},
		{Name: "actionValue", Type: field.TypeJSON},
		{Name: "image", Type: field.TypeString},
	}
	// MonstersTable holds the schema information for the "monsters" table.
	MonstersTable = &schema.Table{
		Name:       "monsters",
		Columns:    MonstersColumns,
		PrimaryKey: []*schema.Column{MonstersColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserconfigsColumns holds the columns for the "userconfigs" table.
	UserconfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "playerID", Type: field.TypeString, Unique: true},
		{Name: "cards", Type: field.TypeJSON},
		{Name: "ladder", Type: field.TypeString},
		{Name: "playerHP", Type: field.TypeInt},
		{Name: "playerEnergy", Type: field.TypeInt},
		{Name: "image", Type: field.TypeString, Nullable: true},
	}
	// UserconfigsTable holds the schema information for the "userconfigs" table.
	UserconfigsTable = &schema.Table{
		Name:       "userconfigs",
		Columns:    UserconfigsColumns,
		PrimaryKey: []*schema.Column{UserconfigsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CardsTable,
		LeaderboardsTable,
		MonstersTable,
		UsersTable,
		UserconfigsTable,
	}
)

func init() {
	CardsTable.Annotation = &entsql.Annotation{
		Table: "cards",
	}
	LeaderboardsTable.Annotation = &entsql.Annotation{
		Table: "leaderboards",
	}
	MonstersTable.Annotation = &entsql.Annotation{
		Table: "monsters",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	UserconfigsTable.Annotation = &entsql.Annotation{
		Table: "userconfigs",
	}
}
