// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cardGame/ent/leaderboard"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LeaderboardCreate is the builder for creating a Leaderboard entity.
type LeaderboardCreate struct {
	config
	mutation *LeaderboardMutation
	hooks    []Hook
}

// SetPlayerID sets the "playerID" field.
func (lc *LeaderboardCreate) SetPlayerID(s string) *LeaderboardCreate {
	lc.mutation.SetPlayerID(s)
	return lc
}

// SetCounts sets the "counts" field.
func (lc *LeaderboardCreate) SetCounts(i int) *LeaderboardCreate {
	lc.mutation.SetCounts(i)
	return lc
}

// Mutation returns the LeaderboardMutation object of the builder.
func (lc *LeaderboardCreate) Mutation() *LeaderboardMutation {
	return lc.mutation
}

// Save creates the Leaderboard in the database.
func (lc *LeaderboardCreate) Save(ctx context.Context) (*Leaderboard, error) {
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LeaderboardCreate) SaveX(ctx context.Context) *Leaderboard {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LeaderboardCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LeaderboardCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LeaderboardCreate) check() error {
	if _, ok := lc.mutation.PlayerID(); !ok {
		return &ValidationError{Name: "playerID", err: errors.New(`ent: missing required field "Leaderboard.playerID"`)}
	}
	if v, ok := lc.mutation.PlayerID(); ok {
		if err := leaderboard.PlayerIDValidator(v); err != nil {
			return &ValidationError{Name: "playerID", err: fmt.Errorf(`ent: validator failed for field "Leaderboard.playerID": %w`, err)}
		}
	}
	if _, ok := lc.mutation.Counts(); !ok {
		return &ValidationError{Name: "counts", err: errors.New(`ent: missing required field "Leaderboard.counts"`)}
	}
	return nil
}

func (lc *LeaderboardCreate) sqlSave(ctx context.Context) (*Leaderboard, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LeaderboardCreate) createSpec() (*Leaderboard, *sqlgraph.CreateSpec) {
	var (
		_node = &Leaderboard{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(leaderboard.Table, sqlgraph.NewFieldSpec(leaderboard.FieldID, field.TypeInt))
	)
	if value, ok := lc.mutation.PlayerID(); ok {
		_spec.SetField(leaderboard.FieldPlayerID, field.TypeString, value)
		_node.PlayerID = value
	}
	if value, ok := lc.mutation.Counts(); ok {
		_spec.SetField(leaderboard.FieldCounts, field.TypeInt, value)
		_node.Counts = value
	}
	return _node, _spec
}

// LeaderboardCreateBulk is the builder for creating many Leaderboard entities in bulk.
type LeaderboardCreateBulk struct {
	config
	err      error
	builders []*LeaderboardCreate
}

// Save creates the Leaderboard entities in the database.
func (lcb *LeaderboardCreateBulk) Save(ctx context.Context) ([]*Leaderboard, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Leaderboard, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LeaderboardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LeaderboardCreateBulk) SaveX(ctx context.Context) []*Leaderboard {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LeaderboardCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LeaderboardCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
