// Code generated by ent, DO NOT EDIT.

package monster

import (
	"cardGame/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Monster {
	return predicate.Monster(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Monster {
	return predicate.Monster(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Monster {
	return predicate.Monster(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Monster {
	return predicate.Monster(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Monster {
	return predicate.Monster(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Monster {
	return predicate.Monster(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Monster {
	return predicate.Monster(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldName, v))
}

// HP applies equality check predicate on the "HP" field. It's identical to HPEQ.
func HP(v int) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldHP, v))
}

// Block applies equality check predicate on the "Block" field. It's identical to BlockEQ.
func Block(v int) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldBlock, v))
}

// Image applies equality check predicate on the "Image" field. It's identical to ImageEQ.
func Image(v string) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldImage, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.Monster {
	return predicate.Monster(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.Monster {
	return predicate.Monster(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.Monster {
	return predicate.Monster(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.Monster {
	return predicate.Monster(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.Monster {
	return predicate.Monster(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.Monster {
	return predicate.Monster(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.Monster {
	return predicate.Monster(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.Monster {
	return predicate.Monster(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.Monster {
	return predicate.Monster(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.Monster {
	return predicate.Monster(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.Monster {
	return predicate.Monster(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.Monster {
	return predicate.Monster(sql.FieldContainsFold(FieldName, v))
}

// HPEQ applies the EQ predicate on the "HP" field.
func HPEQ(v int) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldHP, v))
}

// HPNEQ applies the NEQ predicate on the "HP" field.
func HPNEQ(v int) predicate.Monster {
	return predicate.Monster(sql.FieldNEQ(FieldHP, v))
}

// HPIn applies the In predicate on the "HP" field.
func HPIn(vs ...int) predicate.Monster {
	return predicate.Monster(sql.FieldIn(FieldHP, vs...))
}

// HPNotIn applies the NotIn predicate on the "HP" field.
func HPNotIn(vs ...int) predicate.Monster {
	return predicate.Monster(sql.FieldNotIn(FieldHP, vs...))
}

// HPGT applies the GT predicate on the "HP" field.
func HPGT(v int) predicate.Monster {
	return predicate.Monster(sql.FieldGT(FieldHP, v))
}

// HPGTE applies the GTE predicate on the "HP" field.
func HPGTE(v int) predicate.Monster {
	return predicate.Monster(sql.FieldGTE(FieldHP, v))
}

// HPLT applies the LT predicate on the "HP" field.
func HPLT(v int) predicate.Monster {
	return predicate.Monster(sql.FieldLT(FieldHP, v))
}

// HPLTE applies the LTE predicate on the "HP" field.
func HPLTE(v int) predicate.Monster {
	return predicate.Monster(sql.FieldLTE(FieldHP, v))
}

// BlockEQ applies the EQ predicate on the "Block" field.
func BlockEQ(v int) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldBlock, v))
}

// BlockNEQ applies the NEQ predicate on the "Block" field.
func BlockNEQ(v int) predicate.Monster {
	return predicate.Monster(sql.FieldNEQ(FieldBlock, v))
}

// BlockIn applies the In predicate on the "Block" field.
func BlockIn(vs ...int) predicate.Monster {
	return predicate.Monster(sql.FieldIn(FieldBlock, vs...))
}

// BlockNotIn applies the NotIn predicate on the "Block" field.
func BlockNotIn(vs ...int) predicate.Monster {
	return predicate.Monster(sql.FieldNotIn(FieldBlock, vs...))
}

// BlockGT applies the GT predicate on the "Block" field.
func BlockGT(v int) predicate.Monster {
	return predicate.Monster(sql.FieldGT(FieldBlock, v))
}

// BlockGTE applies the GTE predicate on the "Block" field.
func BlockGTE(v int) predicate.Monster {
	return predicate.Monster(sql.FieldGTE(FieldBlock, v))
}

// BlockLT applies the LT predicate on the "Block" field.
func BlockLT(v int) predicate.Monster {
	return predicate.Monster(sql.FieldLT(FieldBlock, v))
}

// BlockLTE applies the LTE predicate on the "Block" field.
func BlockLTE(v int) predicate.Monster {
	return predicate.Monster(sql.FieldLTE(FieldBlock, v))
}

// ImageEQ applies the EQ predicate on the "Image" field.
func ImageEQ(v string) predicate.Monster {
	return predicate.Monster(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "Image" field.
func ImageNEQ(v string) predicate.Monster {
	return predicate.Monster(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "Image" field.
func ImageIn(vs ...string) predicate.Monster {
	return predicate.Monster(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "Image" field.
func ImageNotIn(vs ...string) predicate.Monster {
	return predicate.Monster(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "Image" field.
func ImageGT(v string) predicate.Monster {
	return predicate.Monster(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "Image" field.
func ImageGTE(v string) predicate.Monster {
	return predicate.Monster(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "Image" field.
func ImageLT(v string) predicate.Monster {
	return predicate.Monster(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "Image" field.
func ImageLTE(v string) predicate.Monster {
	return predicate.Monster(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "Image" field.
func ImageContains(v string) predicate.Monster {
	return predicate.Monster(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "Image" field.
func ImageHasPrefix(v string) predicate.Monster {
	return predicate.Monster(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "Image" field.
func ImageHasSuffix(v string) predicate.Monster {
	return predicate.Monster(sql.FieldHasSuffix(FieldImage, v))
}

// ImageEqualFold applies the EqualFold predicate on the "Image" field.
func ImageEqualFold(v string) predicate.Monster {
	return predicate.Monster(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "Image" field.
func ImageContainsFold(v string) predicate.Monster {
	return predicate.Monster(sql.FieldContainsFold(FieldImage, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Monster) predicate.Monster {
	return predicate.Monster(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Monster) predicate.Monster {
	return predicate.Monster(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Monster) predicate.Monster {
	return predicate.Monster(sql.NotPredicates(p))
}
