// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Monster is the predicate function for monster builders.
type Monster func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserConfig is the predicate function for userconfig builders.
type UserConfig func(*sql.Selector)
